// core/ai/AIResponse.ts

export interface AIUsage {
  readonly inputTokens?: number;

  readonly outputTokens?: number;

  readonly totalTokens?: number;
}

export interface AIResponseMetadata {
  /**
   * Provider that generated the response.
   */
  readonly provider: string;

  /**
   * Actual model ID used.
   */
  readonly model: string;

  /**
   * Original request ID.
   */
  readonly requestId: string;

  /**
   * End-to-end provider latency.
   */
  readonly latencyMs: number;

  /**
   * Provider/runtime finish reason when available.
   */
  readonly finishReason?: string;

  /**
   * Token usage when available.
   */
  readonly usage?: AIUsage;

  /**
   * Whether the response came from a cache.
   */
  readonly cached?: boolean;

  /**
   * Additional provider-specific information.
   */
  readonly details?: Readonly<Record<string, unknown>>;
}

export interface AIResponse {
  readonly text: string;

  readonly metadata: AIResponseMetadata;
}

export interface AIStreamChunk {
  /**
   * Text generated by this chunk.
   */
  readonly text: string;

  /**
   * Original request ID.
   */
  readonly requestId: string;

  /**
   * Provider that generated this chunk.
   */
  readonly provider: string;

  /**
   * Actual model used.
   */
  readonly model: string;

  /**
   * Whether this is the final chunk.
   */
  readonly done: boolean;

  /**
   * Finish reason when available.
   */
  readonly finishReason?: string;
}
