// ============================================================================
// FILE: core/candidate/services/CandidateContextPublisher.ts
//
// PURPOSE:
// Publishes the canonical CandidateContext into the generic Veyra Context
// subsystem.
//
// ARCHITECTURE:
//
//   CandidateProfile
//        +
//   CandidateExperience
//        +
//   CandidateProjects
//        +
//   CandidateSkills
//        +
//   CandidateStories
//        +
//   CandidateEvidence
//        ↓
//   CandidateContextBuilder
//        ↓
//   CandidateContext
//        ↓
//   CandidateContextPublisher
//        ↓
//   ContextManager.index()
//        ↓
//   Context parsing / chunking / embeddings / vector storage
//
// IMPORTANT:
//
// Candidate remains the authority over candidate knowledge.
//
// Context remains the authority over:
//   - generic context ingestion
//   - chunking
//   - embeddings
//   - vector storage
//   - retrieval
//   - ranking
//   - compression
//
// CandidateContextPublisher is therefore an adapter between the two
// subsystems.
//
// core/context NEVER imports Candidate.
//
// Candidate is allowed to publish into Context through the existing
// ContextManager boundary.
// ============================================================================

import type { ContextManager } from "../../context/ContextManager";

import type { CandidateContext } from "../contracts/CandidateContext";

import type { CandidateId } from "../contracts/CandidateTypes";

import { CandidateError } from "../errors/CandidateError";

import { CandidateContextBuilder } from "./CandidateContextBuilder";

// ============================================================================
// REQUEST
// ============================================================================

export interface CandidateContextPublishRequest {
  /**
   * Candidate whose canonical context should be published.
   */
  readonly candidateId: CandidateId;

  /**
   * Optional cancellation signal.
   */
  readonly signal?: AbortSignal;
}

// ============================================================================
// RESULT
// ============================================================================

export interface CandidateContextPublishResult {
  /**
   * Candidate that was published.
   */
  readonly candidateId: CandidateId;

  /**
   * Stable Context item ID.
   */
  readonly contextId: string;

  /**
   * Number of candidate evidence records represented by the generated
   * CandidateContext.
   */
  readonly evidenceCount: number;

  /**
   * Timestamp generated by CandidateContextBuilder.
   */
  readonly generatedAt: string;
}

// ============================================================================
// OPTIONS
// ============================================================================

export interface CandidateContextPublisherOptions {
  /**
   * Candidate-owned canonical context builder.
   */
  readonly contextBuilder: CandidateContextBuilder;

  /**
   * Generic Veyra Context orchestration service.
   */
  readonly contextManager: ContextManager;
}

// ============================================================================
// PUBLISHER
// ============================================================================

export class CandidateContextPublisher {
  private readonly contextBuilder: CandidateContextBuilder;

  private readonly contextManager: ContextManager;

  public constructor(options: CandidateContextPublisherOptions) {
    if (!options) {
      throw CandidateError.invalidRequest(
        "Candidate context publisher options are required.",
        {
          stage: "validation",
        },
      );
    }

    if (!options.contextBuilder) {
      throw CandidateError.invalidRequest(
        "Candidate context builder is required.",
        {
          stage: "context",
        },
      );
    }

    if (!options.contextManager) {
      throw CandidateError.invalidRequest(
        "Context manager is required for candidate context publishing.",
        {
          stage: "context",
        },
      );
    }

    this.contextBuilder = options.contextBuilder;

    this.contextManager = options.contextManager;
  }

  // ==========================================================================
  // PUBLISH
  // ==========================================================================

  /**
   * Build the authoritative CandidateContext and publish it into the generic
   * Context subsystem.
   *
   * This operation deliberately performs no Candidate mutation.
   *
   * CandidateContextBuilder remains responsible for deciding what candidate
   * knowledge belongs in the canonical candidate context.
   *
   * ContextManager is responsible for indexing that representation.
   */
  public async publish(
    request: CandidateContextPublishRequest,
  ): Promise<CandidateContextPublishResult> {
    if (!request) {
      throw CandidateError.invalidRequest(
        "Candidate context publish request is required.",
        {
          stage: "validation",
        },
      );
    }

    const candidateId = this.normalizeCandidateId(request.candidateId);

    this.throwIfAborted(request.signal, candidateId);

    try {
      /**
       * CandidateContextBuilder is the authoritative Candidate-side
       * aggregation layer.
       *
       * It combines:
       *
       *   profile
       *   experiences
       *   projects
       *   skills
       *   stories
       *   candidate evidence
       *
       * into one canonical CandidateContext.
       */
      const candidateContext = await this.contextBuilder.build({
        candidateId,

        signal: request.signal,
      });

      this.throwIfAborted(request.signal, candidateId);

      this.validateCandidateContext(candidateContext, candidateId);

      /**
       * Stable Context identity.
       *
       * Re-publishing the same candidate intentionally targets the same
       * Context item.
       *
       * ContextManager.index() replaces the previous vector representation
       * for the same context ID.
       *
       * Therefore:
       *
       *     candidate update
       *          ↓
       *     publish again
       *          ↓
       *     same context ID
       *          ↓
       *     old vectors replaced
       *
       * This prevents duplicate candidate context records.
       */
      const contextId = this.toContextId(candidateId);

      /**
       * CandidateContext already contains canonical semantic text.
       *
       * We therefore do NOT manually chunk, embed, or store anything here.
       *
       * ContextManager owns that responsibility.
       */
      await this.contextManager.index(
        {
          id: contextId,

          name: `Candidate ${candidateId}`,

          /**
           * ContextContentType uses the generic semantic content category,
           * not an HTTP MIME type.
           *
           * "text/plain" is therefore intentionally NOT used here.
           */
          contentType: "generic",

          source: {
            type: "candidate",

            id: candidateId,

            name: `Candidate ${candidateId}`,

            metadata: {
              candidateId,

              sourceKind: "candidate_context",
            },
          },

          text: candidateContext.text,

          metadata: {
            candidateId,

            sourceKind: "candidate_context",

            generatedAt: candidateContext.generatedAt,

            evidenceCount: candidateContext.evidence.length,

            candidateContextVersion: 1,
          },

          createdAt: candidateContext.generatedAt,

          updatedAt: candidateContext.generatedAt,
        },
        {
          signal: request.signal,
        },
      );

      this.throwIfAborted(request.signal, candidateId);

      return Object.freeze({
        candidateId,

        contextId,

        evidenceCount: candidateContext.evidence.length,

        generatedAt: candidateContext.generatedAt,
      });
    } catch (error) {
      if (error instanceof CandidateError) {
        throw error;
      }

      throw CandidateError.contextBuildFailure(
        "Failed to publish candidate context.",
        {
          candidateId,

          cause: error,

          metadata: {
            integration: "context",

            contextId: this.toContextId(candidateId),
          },
        },
      );
    }
  }

  // ==========================================================================
  // REMOVE
  // ==========================================================================

  /**
   * Removes the Context representation belonging to a candidate.
   *
   * This must be called when a candidate is permanently deleted or when the
   * application intentionally removes candidate knowledge from generic
   * Context.
   */
  public async remove(
    candidateId: CandidateId,
    signal?: AbortSignal,
  ): Promise<void> {
    const normalizedCandidateId = this.normalizeCandidateId(candidateId);

    this.throwIfAborted(signal, normalizedCandidateId);

    try {
      await this.contextManager.remove(
        this.toContextId(normalizedCandidateId),
        {
          signal,
        },
      );

      this.throwIfAborted(signal, normalizedCandidateId);
    } catch (error) {
      if (error instanceof CandidateError) {
        throw error;
      }

      throw CandidateError.contextBuildFailure(
        "Failed to remove candidate context.",
        {
          candidateId: normalizedCandidateId,

          cause: error,

          metadata: {
            integration: "context",

            contextId: this.toContextId(normalizedCandidateId),
          },
        },
      );
    }
  }

  // ==========================================================================
  // VALIDATION
  // ==========================================================================

  private normalizeCandidateId(candidateId: CandidateId): CandidateId {
    if (typeof candidateId !== "string" || !candidateId.trim()) {
      throw CandidateError.invalidRequest(
        "Candidate id is required for context publishing.",
        {
          stage: "validation",
        },
      );
    }

    return candidateId.trim();
  }

  private validateCandidateContext(
    candidateContext: CandidateContext,
    candidateId: CandidateId,
  ): void {
    if (!candidateContext || typeof candidateContext !== "object") {
      throw CandidateError.contextBuildFailure(
        "Candidate context builder returned no context.",
        {
          candidateId,
        },
      );
    }

    if (
      typeof candidateContext.candidateId !== "string" ||
      !candidateContext.candidateId.trim()
    ) {
      throw CandidateError.contextBuildFailure(
        "Candidate context is missing candidateId.",
        {
          candidateId,
        },
      );
    }

    if (candidateContext.candidateId.trim() !== candidateId) {
      throw CandidateError.conflict(
        "Candidate context belongs to a different candidate.",
        {
          stage: "context",
          candidateId,
        },
      );
    }

    if (
      typeof candidateContext.text !== "string" ||
      !candidateContext.text.trim()
    ) {
      throw CandidateError.contextBuildFailure(
        "Candidate context contains no usable text.",
        {
          candidateId,
        },
      );
    }

    if (!Array.isArray(candidateContext.evidence)) {
      throw CandidateError.contextBuildFailure(
        "Candidate context evidence must be an array.",
        {
          candidateId,
        },
      );
    }

    if (
      typeof candidateContext.generatedAt !== "string" ||
      !candidateContext.generatedAt.trim() ||
      !Number.isFinite(Date.parse(candidateContext.generatedAt))
    ) {
      throw CandidateError.contextBuildFailure(
        "Candidate context generatedAt must be a valid date.",
        {
          candidateId,
        },
      );
    }
  }

  // ==========================================================================
  // IDENTIFIERS
  // ==========================================================================

  private toContextId(candidateId: CandidateId): string {
    return `candidate:${candidateId.trim()}`;
  }

  // ==========================================================================
  // CANCELLATION
  // ==========================================================================

  private throwIfAborted(
    signal: AbortSignal | undefined,
    candidateId: CandidateId,
  ): void {
    if (!signal?.aborted) {
      return;
    }

    throw CandidateError.cancelled(candidateId);
  }
}
