// Relative path: desktop/preload/types.ts

/**
 * Veyra Preload API Types
 *
 * This file contains ONLY renderer-safe API contracts.
 *
 * IMPORTANT:
 * - No Node.js APIs are exposed here.
 * - No Electron internals are exposed here.
 * - ipcRenderer is never exposed to the renderer.
 * - HardwareProfiler / ModelManager remain main-process only.
 */

import type {
  HardwareModelPlanResponse,
  HardwareSnapshotResponse,
} from "../../shared/types/hardware";

/**
 * Result returned by Electron window operations.
 */
export interface WindowOperationResult {
  readonly success: boolean;
  readonly reason?: string;
  readonly maximized?: boolean;
}

/**
 * Hardware API exposed to the React renderer.
 */
export interface VeyraHardwareApi {
  /**
   * Gets the cached hardware profile when available.
   *
   * Set forceRefresh=true when a fresh hardware scan is required.
   */
  getProfile(options?: {
    readonly forceRefresh?: boolean;
  }): Promise<HardwareSnapshotResponse>;

  /**
   * Forces a fresh hardware detection.
   */
  refreshProfile(): Promise<HardwareSnapshotResponse>;

  /**
   * Gets the hardware-aware model selection plan.
   *
   * The plan is generated by the main-process ModelManager.
   */
  getModelPlan(options?: {
    readonly forceRefresh?: boolean;
  }): Promise<HardwareModelPlanResponse>;
}

/**
 * Application-level Electron API.
 */
export interface VeyraAppApi {
  getVersion(): Promise<string>;

  getPlatform(): Promise<NodeJS.Platform>;

  getEnvironment(): Promise<"development" | "production">;
}

/**
 * Window-management API.
 */
export interface VeyraWindowApi {
  minimize(): Promise<WindowOperationResult>;

  maximize(): Promise<WindowOperationResult>;

  close(): Promise<WindowOperationResult>;

  isMaximized(): Promise<boolean>;

  isAvailable(): Promise<boolean>;
}

/**
 * Complete Veyra renderer API.
 *
 * This is the ONLY API that should be available through
 * window.veyra.
 */
export interface VeyraDesktopAPI {
  readonly app: VeyraAppApi;

  readonly window: VeyraWindowApi;

  readonly hardware: VeyraHardwareApi;
}

/**
 * Global Window augmentation.
 *
 * React components can safely use:
 *
 * window.veyra.app
 * window.veyra.window
 * window.veyra.hardware
 */
declare global {
  interface Window {
    readonly veyra: VeyraDesktopAPI;
  }
}

export {};
