export declare const ERROR_CODES: {
    readonly UNKNOWN: "UNKNOWN_ERROR";
    readonly VALIDATION_FAILED: "VALIDATION_FAILED";
    readonly UNAUTHORIZED: "UNAUTHORIZED";
    readonly FORBIDDEN: "FORBIDDEN";
    readonly NOT_FOUND: "NOT_FOUND";
    readonly CONFLICT: "CONFLICT";
    readonly RATE_LIMITED: "RATE_LIMITED";
    readonly TIMEOUT: "TIMEOUT";
    readonly AI_PROVIDER_UNAVAILABLE: "AI_PROVIDER_UNAVAILABLE";
    readonly AI_PROVIDER_ERROR: "AI_PROVIDER_ERROR";
    readonly AUDIO_PERMISSION_DENIED: "AUDIO_PERMISSION_DENIED";
    readonly CAPTURE_PERMISSION_DENIED: "CAPTURE_PERMISSION_DENIED";
    readonly STORAGE_ERROR: "STORAGE_ERROR";
    readonly NETWORK_ERROR: "NETWORK_ERROR";
};
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
