// shared/constants/errorCodes.ts
export const ERROR_CODES = {
    UNKNOWN: "UNKNOWN_ERROR",
    VALIDATION_FAILED: "VALIDATION_FAILED",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    CONFLICT: "CONFLICT",
    RATE_LIMITED: "RATE_LIMITED",
    TIMEOUT: "TIMEOUT",
    AI_PROVIDER_UNAVAILABLE: "AI_PROVIDER_UNAVAILABLE",
    AI_PROVIDER_ERROR: "AI_PROVIDER_ERROR",
    AUDIO_PERMISSION_DENIED: "AUDIO_PERMISSION_DENIED",
    CAPTURE_PERMISSION_DENIED: "CAPTURE_PERMISSION_DENIED",
    STORAGE_ERROR: "STORAGE_ERROR",
    NETWORK_ERROR: "NETWORK_ERROR",
};
//# sourceMappingURL=errorCodes.js.map