// shared/constants/events.ts
export const IPC_CHANNELS = {
    APP_GET_VERSION: "app:get-version",
    APP_GET_PLATFORM: "app:get-platform",
    WINDOW_MINIMIZE: "window:minimize",
    WINDOW_MAXIMIZE: "window:maximize",
    WINDOW_CLOSE: "window:close",
    AUDIO_LIST_DEVICES: "audio:list-devices",
    AUDIO_GET_PERMISSION: "audio:get-permission",
    AUDIO_START: "audio:start",
    AUDIO_STOP: "audio:stop",
    CAPTURE_LIST_SOURCES: "capture:list-sources",
    CAPTURE_GET_PERMISSION: "capture:get-permission",
    CAPTURE_START: "capture:start",
    CAPTURE_STOP: "capture:stop",
    SESSION_CREATE: "session:create",
    SESSION_START: "session:start",
    SESSION_PAUSE: "session:pause",
    SESSION_RESUME: "session:resume",
    SESSION_STOP: "session:stop",
    AI_GENERATE: "ai:generate",
    AI_STREAM: "ai:stream",
    AI_HEALTH: "ai:health",
};
//# sourceMappingURL=events.js.map