// shared/types/interviews.ts

import type { ConversationAnalysis } from "./conversation";

import type { InterviewType } from "../constants/interviewTypes";

/**
 * Classification of the current interview/task.
 *
 * This is produced by core/interview.
 */
export interface InterviewClassification {
  readonly type: InterviewType;

  readonly confidence: number;

  readonly alternatives: readonly InterviewClassificationAlternative[];

  readonly signals: readonly string[];
}

/**
 * Alternative classification candidate.
 */
export interface InterviewClassificationAlternative {
  readonly type: InterviewType;

  readonly confidence: number;
}

/**
 * Current interview state.
 *
 * This is deliberately separate from ConversationAnalysis.
 */
export interface InterviewAnalysis {
  readonly classification: InterviewClassification;

  readonly currentTask?: InterviewTask;

  readonly conversation: ConversationAnalysis;

  readonly confidence: number;

  readonly signals: readonly string[];
}

/**
 * Task being performed by the interviewer/candidate.
 */
export interface InterviewTask {
  readonly id: string;

  readonly type: InterviewType;

  readonly questionText: string;

  readonly requiresResponse: boolean;

  readonly confidence: number;
}

/**
 * Cross-boundary answer guidance.
 *
 * This is a DTO describing guidance generated by the interview domain.
 *
 * The actual answer generation belongs to core/interview + core/ai.
 */
export interface InterviewAnswerGuidance {
  readonly type: InterviewType;

  readonly headline?: string;

  readonly talkingPoints: readonly string[];

  readonly cautions: readonly string[];

  readonly confidence: number;
}

/**
 * Cross-boundary interview request.
 *
 * This is useful when client/desktop/server needs to request
 * interview analysis.
 */
export interface InterviewAnalysisRequest {
  readonly conversation: ConversationAnalysis;
}
